### ISSUE TITLE
tests require running redis instance

### ISSUE THREAD

**Issue by b1-88er** [df3n5/redact-py#2]
To run unittests redis instance on default port is needed. This should be solved by running redis by the test runtime on the random/available port.

**Comment by jonathanfrawley** [comment]
Yep this is a valid point, I will come up with a better setup for this soon.

**Comment by b1-88er** [comment]
you might want to take a look to pytest-dbfixtures package.

**Comment by b1-88er** [comment]
I don't care anymore.
